name: Build and Upload Release Assets

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Linux binary
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -v -o bin/dchook-linux .

      - name: Build Windows binary
        run: |
          mkdir -p bin
          GOOS=windows GOARCH=amd64 go build -v -o bin/dchook-windows.exe .

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
