name: Go

on:
  push:
    tags:
      - 'V*'


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: |
          mkdir -p bin
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            GOOS=windows
            OUTPUT=bin/dchook-windows.exe
          else
            GOOS=linux
            OUTPUT=bin/dchook-linux
          fi
          GOARCH=amd64
          env GOOS=$GOOS GOARCH=$GOARCH go build -v -o $OUTPUT .

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
